name: exercise_book
version: "1.0.0"
config-version: 2

profile: exercise_book

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  exercise_book:
    bronze:
      +materialized: incremental
      +schema: bronze
      +meta:
        dagster:
          group: bronze
